name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node
      run: |
        apt-get install npm
        npm install --global yarn
        npm install -g n
        n stable

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.5

    - name: Build
      run: |
          cd net/server
          go build databag
          
    - name: Test
      run: |
          cd net/server
          go test -v ./...
